sudo: required
services:
    - docker

before_install:
    - docker build -t jibinrajck/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true jibinrajck/docker-react npm run test -- --coverage