sudo: required
services:
    - docker

before_install:
    - docker build -t jibinrajck/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true jibinrajck/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-088710337221"
    bucket_path: "Docker-react"
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY